### ISSUE TITLE
Replace local license checks with the SymbiFlow/actions/checks@main action

### ISSUE THREAD

**Issue by mithro** [chipsalliance/sv-tests#1449]
https://github.com/SymbiFlow/sv-tests/blob/8b14f75bc1c3d15d6a5a2ba217800e242f4f5f3e/.github/workflows/sv-tests-ci.yml#L30-L32

https://github.com/SymbiFlow/actions/tree/main/checks

**Comment by mithro** [comment]
Example at https://github.com/SymbiFlow/symbiflow-rr-graph/blob/master/.github/workflows/licensing.yml

**Comment by tgorochowik** [comment]
This has been done in #1472
