### ISSUE TITLE
earlgrey core is not configured correctly

### ISSUE THREAD

**Issue by MikePopoloski** [chipsalliance/sv-tests#1564]
It seems that the earlgrey core is not including files that it needs in order to elaborate. For example, the package "pwrmgr_reg_pkg" is not included. It's listed as a dependency in the fusesoc core but never ends up in the generated lowrisc_systems_top_earlgrey_0.1.scr file, so I assume there's a problem related to collecting transitive dependencies. I don't know enough about fusesoc to know if this is a misconfig in sv-tests, in the earlgrey core file, or a bug in the fusesoc tool itself. It does need to be fixed though, because otherwise the core is not able to be elaborated.

**Comment by RRozak** [comment]
Fixed by https://github.com/chipsalliance/sv-tests/pull/2116
