### ISSUE TITLE
Minor bug in the fixed header [firefox]

### ISSUE THREAD

**Issue by Prahitha** [chipsalliance/sv-tests#1689]
The toolnames don't disappear after scrolling past the corresponding column - visible after scrolling down a bit.
![bug_firefox](https://user-images.githubusercontent.com/44160152/129344250-a3d6b493-1bf5-43fe-ab6f-de27f39bdfb4.png)

**Comment by hzeller** [comment]
Confirmed behavior with firefox 78.12.0.
Current Chrome works as expected (sideways scrolled tool-names disappear).

So probably some disagreement about interpretation of the CSS for the different browsers.

**Comment by tgorochowik** [comment]
Fixed in #1919
