### ISSUE TITLE
Tools not being updated again

### ISSUE THREAD

**Issue by MikePopoloski** [chipsalliance/sv-tests#1744]
Tool dependencies seem to be not getting updated again. The generated dashboard seems to have tool versions that are about a month old for several that I checked (slang, Surelog, verible). I've lost track of where the actual versions are coming from these days; conda, GitHub actions, submodules via dependabot? Regardless, it would be nice to see up-to-date tool versions used.

**Comment by mithro** [comment]
We really need something which alerts if these tools are not being updated...

**Comment by mithro** [comment]
@hzeller - Who should own this?

**Comment by hzeller** [comment]
This should be owend by @tgorochowik 
I suspect it also depends on work by @QuantamHD to get cloud runner machines available.

**Comment by mithro** [comment]
Can we set up some type of alerting so that we know when this happens?

**Comment by MikePopoloski** [comment]
Looks like the builds are failing again? At least from what I can tell here: https://github.com/hdl/conda-eda/actions

**Comment by kamilrakoczy** [comment]
The builds should be fixed after: https://github.com/hdl/conda-eda/pull/131

**Comment by alaindargelas** [comment]
At least Surelog is not being updated anymore, I don't know about the other tools.

**Comment by tgorochowik** [comment]
@alaindargelas as we discussed offline, we are back to using submodules to generate the report. This way there is more control over what is built when. The submodules are bumped weekly, if you need more frequent updates, feel free to bump the submodule more often.

Thanks!

**Comment by alaindargelas** [comment]
I'm saying the Surelog submodule has not been updated in over 2 weeks. I did not nor intend to trigger an update manually.
So something is broken in the automatic update.
Surelog version should read 1.14, it is stuck at 1.13.
