### ISSUE TITLE
uhdmyosys all failing due to missing shared library

### ISSUE THREAD

**Issue by hzeller** [chipsalliance/sv-tests#1758]
Failures look all like this
```
uhdm-yosys: error while loading shared libraries: libffi.so.7: cannot open shared object file: No such file or directory
```

I suspect something available on the conda build machine but not here ?

**Comment by hzeller** [comment]
Not sure if  Tom is back in the office, if not, maybe Karol can triage ?

**Comment by tgorochowik** [comment]
Fixed in the issue linked above
