### ISSUE TITLE
Link to UTD-SV tests broken on sv-tests-results page

### ISSUE THREAD

**Issue by sw23** [chipsalliance/sv-tests#1827]
There's currently a broken link on this page:
https://chipsalliance.github.io/sv-tests-results/

Tests imported from utd-SystemVerilog -> https://github.com/SymbiFlow/sv-tests/tree/master/third_party/tests/utd-sv

It appears these tests are being migrated to this repo:
https://github.com/SymbiFlow/sv-tests/tree/main/
"This repository has been moved to: https://github.com/chipsalliance/sv-tests"

However the chipsalliance/sv-tests repo still points to the old repo via a submodule:
https://github.com/chipsalliance/sv-tests/tree/master/third_party/tests
https://github.com/chipsalliance/sv-tests/blob/710803e831bc89f38c5d0a07157377adc2350938/.gitmodules#L77

Not sure what the long-term plan is, but it's probably be good to fix the link in the interim

**Comment by tgorochowik** [comment]
Fixed by #1828
