### ISSUE TITLE
BlackParrot setup for UhdmYosys

### ISSUE THREAD

**Issue by alaindargelas** [chipsalliance/sv-tests#2046]
For plain Surelog, the command line contains -lowmem and --top-module:

surelog -nopython -parse -nonote -noinfo -nowarning -sverilog --top-module bp_be_top -lowmem .....

For uhdmyosys, both options are missing (Yielding an out of memory):

surelog -nopython -nobuiltin -parse -sverilog -nonote -noinfo -nowarning ....

**Comment by alaindargelas** [comment]
Should BlackParrot be moved the "Cores" list in sv-tests?

**Comment by tgorochowik** [comment]
Both issues have been addressed, thanks
