### ISSUE TITLE
Check the uvm test suite is being used correctly

### ISSUE THREAD

**Issue by mithro** [chipsalliance/sv-tests#618]
The UVM test suite in https://github.com/SymbiFlow/sv-tests/tree/master/third_party/tests/uvm is showing only 1 test but has a lot more files than a single one.

It is unclear to me if the tools are actually parsing more than a single file which has an include....

**Comment by alainmarcel** [comment]
See #560

**Comment by tgorochowik** [comment]
Let's close it, there are now multiple valid uvm tests available
